server:
  port: 7088

spring:
  profiles:
    active: native

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka